version: '3.8'

services:
  musicbot:
    build: .
    container_name: telegram_music_bot
    restart: unless-stopped
    
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - SESSION_STRING=${SESSION_STRING}
      - SESSION_NAME=${SESSION_NAME:-MusicBot_Session}
      - BOT_USERNAME=${BOT_USERNAME}
      - BOT_NAME=${BOT_NAME:-Music Bot}
      - OWNER_USERNAME=${OWNER_USERNAME}
      - OWNER_ID=${OWNER_ID}
      - SUDO_USERS=${SUDO_USERS}
      - GROUP_SUPPORT=${GROUP_SUPPORT}
      - UPDATES_CHANNEL=${UPDATES_CHANNEL}
      - AUTO_JOIN_CHANNELS=${AUTO_JOIN_CHANNELS:-RR3R2 xl444}
      - MONGODB_URL=${MONGODB_URL}
      - DURATION_LIMIT=${DURATION_LIMIT:-60}
      - COMMAND_PREFIXES=${COMMAND_PREFIXES:-شغل تشغيل ش}
      - AUTO_LEAVING_ASSISTANT=${AUTO_LEAVING_ASSISTANT:-true}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - GENIUS_API_TOKEN=${GENIUS_API_TOKEN}
    
    volumes:
      - ./downloads:/app/downloads
      - ./logs:/app/logs
      - ./cache:/app/cache

networks:
  default:
    name: musicbot_network
